export const OBJECT_EVENT_GRAPHICS = [
  { id: 0, macro: "BRENDAN_NORMAL", name: "小悠普通" },
  { id: 1, macro: "BRENDAN_MACH_BIKE", name: "小悠音速自行车" },
  { id: 2, macro: "BRENDAN_SURFING", name: "小悠冲浪" },
  { id: 3, macro: "BRENDAN_FIELD_MOVE", name: "小悠使用秘传招式" },
  { id: 4, macro: "QUINTY_PLUMP", name: "胖女孩 / Quinty" },
  { id: 5, macro: "NINJA_BOY", name: "忍者小子" },
  { id: 6, macro: "TWIN", name: "双胞胎" },
  { id: 7, macro: "BOY_1", name: "男孩 1" },
  { id: 8, macro: "GIRL_1", name: "女孩 1" },
  { id: 9, macro: "BOY_2", name: "男孩 2" },
  { id: 10, macro: "GIRL_2", name: "女孩 2" },
  { id: 11, macro: "LITTLE_BOY", name: "小男孩" },
  { id: 12, macro: "LITTLE_GIRL", name: "小女孩" },
  { id: 13, macro: "BOY_3", name: "男孩 3" },
  { id: 14, macro: "GIRL_3", name: "女孩 3" },
  { id: 15, macro: "RICH_BOY", name: "富家少爷" },
  { id: 16, macro: "WOMAN_1", name: "女性 1" },
  { id: 17, macro: "FAT_MAN", name: "胖男人" },
  { id: 18, macro: "POKEFAN_F", name: "宝可梦迷女" },
  { id: 19, macro: "MAN_1", name: "男性 1" },
  { id: 20, macro: "WOMAN_2", name: "女性 2" },
  { id: 21, macro: "EXPERT_M", name: "达人男" },
  { id: 22, macro: "EXPERT_F", name: "达人女" },
  { id: 23, macro: "MAN_2", name: "男性 2" },
  { id: 24, macro: "WOMAN_3", name: "女性 3" },
  { id: 25, macro: "POKEFAN_M", name: "宝可梦迷男" },
  { id: 26, macro: "WOMAN_4", name: "女性 4" },
  { id: 27, macro: "COOK", name: "厨师" },
  { id: 28, macro: "LINK_RECEPTIONIST", name: "通信接待员" },
  { id: 29, macro: "OLD_MAN", name: "老爷爷" },
  { id: 30, macro: "OLD_WOMAN", name: "老奶奶" },
  { id: 31, macro: "CAMPER", name: "露营少年" },
  { id: 32, macro: "PICNICKER", name: "野餐少女" },
  { id: 33, macro: "MAN_3", name: "男性 3" },
  { id: 34, macro: "WOMAN_5", name: "女性 5" },
  { id: 35, macro: "YOUNGSTER", name: "短裤小子" },
  { id: 36, macro: "BUG_CATCHER", name: "捕虫少年" },
  { id: 37, macro: "PSYCHIC_M", name: "超能力者男" },
  { id: 38, macro: "SCHOOL_KID_M", name: "学生男" },
  { id: 39, macro: "MANIAC", name: "怪兽狂 / 狂热者" },
  { id: 40, macro: "HEX_MANIAC", name: "灵异迷" },
  { id: 41, macro: "RAYQUAZA_STILL", name: "静止烈空坐" },
  { id: 42, macro: "SWIMMER_M", name: "游泳男" },
  { id: 43, macro: "SWIMMER_F", name: "游泳女" },
  { id: 44, macro: "BLACK_BELT", name: "空手道王" },
  { id: 45, macro: "BEAUTY", name: "大姐姐 / 美女" },
  { id: 46, macro: "SCIENTIST_1", name: "科学家 1" },
  { id: 47, macro: "LASS", name: "迷你裙" },
  { id: 48, macro: "GENTLEMAN", name: "绅士" },
  { id: 49, macro: "SAILOR", name: "水手" },
  { id: 50, macro: "FISHERMAN", name: "钓鱼人" },
  { id: 51, macro: "RUNNING_TRIATHLETE_M", name: "跑步铁人三项男" },
  { id: 52, macro: "RUNNING_TRIATHLETE_F", name: "跑步铁人三项女" },
  { id: 53, macro: "TUBER_F", name: "泳圈女孩" },
  { id: 54, macro: "TUBER_M", name: "泳圈男孩" },
  { id: 55, macro: "HIKER", name: "登山男" },
  { id: 56, macro: "CYCLING_TRIATHLETE_M", name: "骑车铁人三项男" },
  { id: 57, macro: "CYCLING_TRIATHLETE_F", name: "骑车铁人三项女" },
  { id: 58, macro: "NURSE", name: "护士" },
  { id: 59, macro: "ITEM_BALL", name: "精灵球道具" },
  { id: 60, macro: "BERRY_TREE", name: "树果树" },
  { id: 61, macro: "BERRY_TREE_EARLY_STAGES", name: "树果树早期阶段" },
  { id: 62, macro: "BERRY_TREE_LATE_STAGES", name: "树果树后期阶段" },
  { id: 63, macro: "BRENDAN_ACRO_BIKE", name: "小悠越野自行车" },
  { id: 64, macro: "PROF_BIRCH", name: "小田卷博士" },
  { id: 65, macro: "MAN_4", name: "男性 4" },
  { id: 66, macro: "MAN_5", name: "男性 5" },
  { id: 67, macro: "REPORTER_M", name: "记者男" },
  { id: 68, macro: "REPORTER_F", name: "记者女" },
  { id: 69, macro: "BARD", name: "吟游诗人" },
  { id: 70, macro: "ANABEL", name: "莉拉" },
  { id: 71, macro: "TUCKER", name: "希尔斯" },
  { id: 72, macro: "GRETA", name: "黄瓜香" },
  { id: 73, macro: "SPENSER", name: "宇康" },
  { id: 74, macro: "NOLAND", name: "达拉" },
  { id: 75, macro: "LUCY", name: "小蓟" },
  { id: 76, macro: "UNUSED_NATU_DOLL", name: "未使用天然雀玩偶" },
  { id: 77, macro: "UNUSED_MAGNEMITE_DOLL", name: "未使用小磁怪玩偶" },
  { id: 78, macro: "UNUSED_SQUIRTLE_DOLL", name: "未使用杰尼龟玩偶" },
  { id: 79, macro: "UNUSED_WOOPER_DOLL", name: "未使用乌波玩偶" },
  { id: 80, macro: "UNUSED_PIKACHU_DOLL", name: "未使用皮卡丘玩偶" },
  { id: 81, macro: "UNUSED_PORYGON2_DOLL", name: "未使用多边兽Ⅱ玩偶" },
  { id: 82, macro: "CUTTABLE_TREE", name: "可砍树" },
  { id: 83, macro: "MART_EMPLOYEE", name: "商店店员" },
  { id: 84, macro: "ROOFTOP_SALE_WOMAN", name: "屋顶特卖女士" },
  { id: 85, macro: "TEALA", name: "Teala / NPC 名" },
  { id: 86, macro: "BREAKABLE_ROCK", name: "可碎岩石" },
  { id: 87, macro: "PUSHABLE_BOULDER", name: "可推动巨石" },
  { id: 88, macro: "MR_BRINEYS_BOAT", name: "哈奇老人的船" },
  { id: 89, macro: "MAY_NORMAL", name: "小遥普通" },
  { id: 90, macro: "MAY_MACH_BIKE", name: "小遥音速自行车" },
  { id: 91, macro: "MAY_ACRO_BIKE", name: "小遥越野自行车" },
  { id: 92, macro: "MAY_SURFING", name: "小遥冲浪" },
  { id: 93, macro: "MAY_FIELD_MOVE", name: "小遥使用秘传招式" },
  { id: 94, macro: "TRUCK", name: "搬家卡车" },
  { id: 95, macro: "VIGOROTH_CARRYING_BOX", name: "搬箱子的过动猿" },
  { id: 96, macro: "VIGOROTH_FACING_AWAY", name: "背对的过动猿" },
  { id: 97, macro: "BIRCHS_BAG", name: "小田卷博士的包" },
  { id: 98, macro: "ZIGZAGOON_1", name: "蛇纹熊 1" },
  { id: 99, macro: "ARTIST", name: "艺术家" },
  { id: 100, macro: "RIVAL_BRENDAN_NORMAL", name: "对手小悠普通" },
  { id: 101, macro: "RIVAL_BRENDAN_MACH_BIKE", name: "对手小悠音速自行车" },
  { id: 102, macro: "RIVAL_BRENDAN_ACRO_BIKE", name: "对手小悠越野自行车" },
  { id: 103, macro: "RIVAL_BRENDAN_SURFING", name: "对手小悠冲浪" },
  { id: 104, macro: "RIVAL_BRENDAN_FIELD_MOVE", name: "对手小悠使用秘传招式" },
  { id: 105, macro: "RIVAL_MAY_NORMAL", name: "对手小遥普通" },
  { id: 106, macro: "RIVAL_MAY_MACH_BIKE", name: "对手小遥音速自行车" },
  { id: 107, macro: "RIVAL_MAY_ACRO_BIKE", name: "对手小遥越野自行车" },
  { id: 108, macro: "RIVAL_MAY_SURFING", name: "对手小遥冲浪" },
  { id: 109, macro: "RIVAL_MAY_FIELD_MOVE", name: "对手小遥使用秘传招式" },
  { id: 110, macro: "CAMERAMAN", name: "摄影师" },
  { id: 111, macro: "BRENDAN_UNDERWATER", name: "小悠水下" },
  { id: 112, macro: "MAY_UNDERWATER", name: "小遥水下" },
  { id: 113, macro: "MOVING_BOX", name: "搬家箱子" },
  { id: 114, macro: "CABLE_CAR", name: "缆车" },
  { id: 115, macro: "SCIENTIST_2", name: "科学家 2" },
  { id: 116, macro: "DEVON_EMPLOYEE", name: "得文员工" },
  { id: 117, macro: "AQUA_MEMBER_M", name: "水舰队男成员" },
  { id: 118, macro: "AQUA_MEMBER_F", name: "水舰队女成员" },
  { id: 119, macro: "MAGMA_MEMBER_M", name: "熔岩队男成员" },
  { id: 120, macro: "MAGMA_MEMBER_F", name: "熔岩队女成员" },
  { id: 121, macro: "SIDNEY", name: "花月" },
  { id: 122, macro: "PHOEBE", name: "芙蓉" },
  { id: 123, macro: "GLACIA", name: "波妮" },
  { id: 124, macro: "DRAKE", name: "源治" },
  { id: 125, macro: "ROXANNE", name: "杜鹃" },
  { id: 126, macro: "BRAWLY", name: "藤树" },
  { id: 127, macro: "WATTSON", name: "铁旋" },
  { id: 128, macro: "FLANNERY", name: "亚莎" },
  { id: 129, macro: "NORMAN", name: "千里" },
  { id: 130, macro: "WINONA", name: "娜琪" },
  { id: 131, macro: "LIZA", name: "枫" },
  { id: 132, macro: "TATE", name: "南" },
  { id: 133, macro: "WALLACE", name: "米可利" },
  { id: 134, macro: "STEVEN", name: "大吾" },
  { id: 135, macro: "WALLY", name: "满充" },
  { id: 136, macro: "LITTLE_BOY_3", name: "小男孩 3" },
  { id: 137, macro: "BRENDAN_FISHING", name: "小悠钓鱼" },
  { id: 138, macro: "MAY_FISHING", name: "小遥钓鱼" },
  { id: 139, macro: "HOT_SPRINGS_OLD_WOMAN", name: "温泉老奶奶" },
  { id: 140, macro: "SS_TIDAL", name: "破浪号" },
  { id: 141, macro: "SUBMARINE_SHADOW", name: "潜水艇影子" },
  { id: 142, macro: "PICHU_DOLL", name: "皮丘玩偶" },
  { id: 143, macro: "PIKACHU_DOLL", name: "皮卡丘玩偶" },
  { id: 144, macro: "MARILL_DOLL", name: "玛力露玩偶" },
  { id: 145, macro: "TOGEPI_DOLL", name: "波克比玩偶" },
  { id: 146, macro: "CYNDAQUIL_DOLL", name: "火球鼠玩偶" },
  { id: 147, macro: "CHIKORITA_DOLL", name: "菊草叶玩偶" },
  { id: 148, macro: "TOTODILE_DOLL", name: "小锯鳄玩偶" },
  { id: 149, macro: "JIGGLYPUFF_DOLL", name: "胖丁玩偶" },
  { id: 150, macro: "MEOWTH_DOLL", name: "喵喵玩偶" },
  { id: 151, macro: "CLEFAIRY_DOLL", name: "皮皮玩偶" },
  { id: 152, macro: "DITTO_DOLL", name: "百变怪玩偶" },
  { id: 153, macro: "SMOOCHUM_DOLL", name: "迷唇娃玩偶" },
  { id: 154, macro: "TREECKO_DOLL", name: "木守宫玩偶" },
  { id: 155, macro: "TORCHIC_DOLL", name: "火稚鸡玩偶" },
  { id: 156, macro: "MUDKIP_DOLL", name: "水跃鱼玩偶" },
  { id: 157, macro: "DUSKULL_DOLL", name: "夜巡灵玩偶" },
  { id: 158, macro: "WYNAUT_DOLL", name: "小果然玩偶" },
  { id: 159, macro: "BALTOY_DOLL", name: "天秤偶玩偶" },
  { id: 160, macro: "KECLEON_DOLL", name: "变隐龙玩偶" },
  { id: 161, macro: "AZURILL_DOLL", name: "露力丽玩偶" },
  { id: 162, macro: "SKITTY_DOLL", name: "向尾喵玩偶" },
  { id: 163, macro: "SWABLU_DOLL", name: "青绵鸟玩偶" },
  { id: 164, macro: "GULPIN_DOLL", name: "溶食兽玩偶" },
  { id: 165, macro: "LOTAD_DOLL", name: "莲叶童子玩偶" },
  { id: 166, macro: "SEEDOT_DOLL", name: "橡实果玩偶" },
  { id: 167, macro: "PIKA_CUSHION", name: "皮卡丘靠垫" },
  { id: 168, macro: "ROUND_CUSHION", name: "圆形靠垫" },
  { id: 169, macro: "KISS_CUSHION", name: "亲吻靠垫" },
  { id: 170, macro: "ZIGZAG_CUSHION", name: "之字靠垫" },
  { id: 171, macro: "SPIN_CUSHION", name: "旋转靠垫" },
  { id: 172, macro: "DIAMOND_CUSHION", name: "菱形靠垫" },
  { id: 173, macro: "BALL_CUSHION", name: "球形靠垫" },
  { id: 174, macro: "GRASS_CUSHION", name: "草靠垫" },
  { id: 175, macro: "FIRE_CUSHION", name: "火靠垫" },
  { id: 176, macro: "WATER_CUSHION", name: "水靠垫" },
  { id: 177, macro: "BIG_SNORLAX_DOLL", name: "大卡比兽玩偶" },
  { id: 178, macro: "BIG_RHYDON_DOLL", name: "大钻角犀兽玩偶" },
  { id: 179, macro: "BIG_LAPRAS_DOLL", name: "大拉普拉斯玩偶" },
  { id: 180, macro: "BIG_VENUSAUR_DOLL", name: "大妙蛙花玩偶" },
  { id: 181, macro: "BIG_CHARIZARD_DOLL", name: "大喷火龙玩偶" },
  { id: 182, macro: "BIG_BLASTOISE_DOLL", name: "大水箭龟玩偶" },
  { id: 183, macro: "BIG_WAILMER_DOLL", name: "大吼吼鲸玩偶" },
  { id: 184, macro: "BIG_REGIROCK_DOLL", name: "大雷吉洛克玩偶" },
  { id: 185, macro: "BIG_REGICE_DOLL", name: "大雷吉艾斯" },
  { id: 186, macro: "BIG_REGISTEEL_DOLL", name: "大雷吉斯奇鲁玩偶" },
  { id: 187, macro: "LATIAS", name: "拉帝亚斯" },
  { id: 188, macro: "LATIOS", name: "拉帝欧斯" },
  { id: 189, macro: "GAMEBOY_KID", name: "游戏男孩少年" },
  { id: 190, macro: "CONTEST_JUDGE", name: "华丽大赛评委" },
  { id: 191, macro: "BRENDAN_WATERING", name: "小悠浇水" },
  { id: 192, macro: "MAY_WATERING", name: "小遥浇水" },
  { id: 193, macro: "BRENDAN_DECORATING", name: "小悠装饰" },
  { id: 194, macro: "MAY_DECORATING", name: "小遥装饰" },
  { id: 195, macro: "ARCHIE", name: "水梧桐" },
  { id: 196, macro: "MAXIE", name: "赤焰松" },
  { id: 197, macro: "KYOGRE_FRONT", name: "盖欧卡正面" },
  { id: 198, macro: "GROUDON_FRONT", name: "固拉多正面" },
  { id: 199, macro: "FOSSIL", name: "化石" },
  { id: 200, macro: "REGIROCK", name: "雷吉洛克" },
  { id: 201, macro: "REGICE", name: "雷吉艾斯" },
  { id: 202, macro: "REGISTEEL", name: "雷吉斯奇鲁" },
  { id: 203, macro: "SKITTY", name: "向尾喵" },
  { id: 204, macro: "KECLEON", name: "变隐龙" },
  { id: 205, macro: "KYOGRE_ASLEEP", name: "沉睡盖欧卡" },
  { id: 206, macro: "GROUDON_ASLEEP", name: "沉睡固拉多" },
  { id: 207, macro: "RAYQUAZA", name: "烈空坐" },
  { id: 208, macro: "ZIGZAGOON_2", name: "蛇纹熊 2" },
  { id: 209, macro: "PIKACHU", name: "皮卡丘" },
  { id: 210, macro: "AZUMARILL", name: "玛力露丽" },
  { id: 211, macro: "WINGULL", name: "长翅鸥" },
  { id: 212, macro: "KECLEON_BRIDGE_SHADOW", name: "桥上变隐龙影子" },
  { id: 213, macro: "TUBER_M_SWIMMING", name: "游泳泳圈男孩" },
  { id: 214, macro: "AZURILL", name: "露力丽" },
  { id: 215, macro: "MOM", name: "妈妈" },
  { id: 216, macro: "LINK_BRENDAN", name: "通信小悠" },
  { id: 217, macro: "LINK_MAY", name: "通信小遥" },
  { id: 218, macro: "JUAN", name: "亚当" },
  { id: 219, macro: "SCOTT", name: "亚希达" },
  { id: 220, macro: "POOCHYENA", name: "土狼犬" },
  { id: 221, macro: "KYOGRE_SIDE", name: "盖欧卡侧面" },
  { id: 222, macro: "GROUDON_SIDE", name: "固拉多侧面" },
  { id: 223, macro: "MYSTERY_GIFT_MAN", name: "神秘礼物男子" },
  { id: 224, macro: "TRICK_HOUSE_STATUE", name: "戏法屋雕像" },
  { id: 225, macro: "KIRLIA", name: "奇鲁莉安" },
  { id: 226, macro: "DUSCLOPS", name: "彷徨夜灵" },
  { id: 227, macro: "UNION_ROOM_NURSE", name: "联合房间护士" },
  { id: 228, macro: "SUDOWOODO", name: "树才怪" },
  { id: 229, macro: "MEW", name: "梦幻" },
  { id: 230, macro: "RED", name: "赤红" },
  { id: 231, macro: "LEAF", name: "叶子" },
  { id: 232, macro: "DEOXYS", name: "代欧奇希斯" },
  { id: 233, macro: "DEOXYS_TRIANGLE", name: "代欧奇希斯三角" },
  { id: 234, macro: "BRANDON", name: "神代" },
  { id: 235, macro: "LINK_RS_BRENDAN", name: "通信 RS 小悠" },
  { id: 236, macro: "LINK_RS_MAY", name: "通信 RS 小遥" },
  { id: 237, macro: "LUGIA", name: "洛奇亚" },
  { id: 238, macro: "HOOH", name: "凤王" },
  { id: 239, macro: "DYNAMIC_OBJECT_239", name: "动态对象239" },
  { id: 240, macro: "DYNAMIC_OBJECT_240", name: "动态对象240" },
  { id: 241, macro: "DYNAMIC_OBJECT_241", name: "劲敌" },
  { id: 242, macro: "DYNAMIC_OBJECT_242", name: "动态对象242" },
  { id: 243, macro: "DYNAMIC_OBJECT_243", name: "动态对象243" },
  { id: 244, macro: "DYNAMIC_OBJECT_244", name: "动态对象244" },
  { id: 245, macro: "DYNAMIC_OBJECT_245", name: "动态对象245" },
  { id: 246, macro: "DYNAMIC_OBJECT_246", name: "动态对象246" },
  { id: 247, macro: "DYNAMIC_OBJECT_247", name: "动态对象247" },
  { id: 248, macro: "DYNAMIC_OBJECT_248", name: "动态对象248" },
  { id: 249, macro: "DYNAMIC_OBJECT_249", name: "动态对象249" },
  { id: 250, macro: "DYNAMIC_OBJECT_250", name: "动态对象250" },
  { id: 251, macro: "DYNAMIC_OBJECT_251", name: "动态对象251" },
  { id: 252, macro: "DYNAMIC_OBJECT_252", name: "动态对象252" },
  { id: 253, macro: "DYNAMIC_OBJECT_253", name: "动态对象253" },
  { id: 254, macro: "DYNAMIC_OBJECT_254", name: "动态对象254" },
  { id: 255, macro: "DYNAMIC_OBJECT_255", name: "动态对象255" },
]

export const OBJECT_EVENT_GRAPHICS_BY_ID = new Map(
  OBJECT_EVENT_GRAPHICS.map(item => [item.id, item]),
)

export function formatObjectEventGraphicsHex(value) {
  const numberValue = Number(value)
  if (!Number.isInteger(numberValue)) return "0x??"
  return `0x${numberValue.toString(16).toUpperCase().padStart(2, "0")}`
}

export function getObjectEventGraphics(value) {
  return OBJECT_EVENT_GRAPHICS_BY_ID.get(Number(value)) || null
}

export function formatObjectEventGraphicsLabel(value) {
  const item = getObjectEventGraphics(value)
  const hex = formatObjectEventGraphicsHex(value)
  return item ? `${item.name}` : `${hex} 未知图形`
}

export const OBJECT_EVENT_GRAPHICS_OPTIONS = OBJECT_EVENT_GRAPHICS.map(item => ({
  value: item.id,
  label: formatObjectEventGraphicsLabel(item.id),
  // searchText: `${item.id} ${formatObjectEventGraphicsHex(item.id)} ${item.name} ${item.macro}`.toLowerCase(),
  searchText: `${item.name}`.toLowerCase(),
}))
